services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=stackoverflow_light'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '500MB'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
